# Generated by Django 2.1.2 on 2018-10-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='thisQuestionId',
            field=models.IntegerField(default=0),
        ),
    ]
